# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Installing deadsnakes
      run: |
        sudo apt-get install -y apt-utils software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3-venv python3.8 python3.9 python3.10 python3.11 python3.12 virtualenv
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools flake8 tox
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $HOME/.local/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $HOME/.local/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with tox
      run: |
        $HOME/.local/bin/tox
